# Project             :   Screenipy
# Author              :   Pranjal Joshi
# Created             :   27/04/2021
# Description         :   Workflow for CI - Testing source and PR main for release


name: Screenipy Build - Docker for Streamlit UI
on:
  push:
    branches: [ streamlit-ui ]
  pull_request:
    branches: [ streamlit-ui ]

jobs:

  Streamlit-Docker-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: streamlit-ui

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Dev Build and Docker Push
      run: |
        docker build -t screeni-py:gui .
        docker tag screeni-py:gui joshipranjal/screeni-py:gui
        docker push joshipranjal/screeni-py:gui